# Generated by Django 6.0.3 on 2026-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('task', 'Task 📝'), ('bug', 'Bug / Issue 🐛'), ('feature', 'Feature Request ✨'), ('maintenance', 'Maintenance 🛠️')], default='task', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
