# Generated by Django 5.2.3 on 2026-09-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('done', 'Done'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
