# Generated by Django 5.2.3 on 2026-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_todoitem_todosharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='todosharerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='todosharerequest',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
