# Generated by Django 5.2.3 on 2026-09-21 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_todosharerequest_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('todo_created', 'Todo Created 📝'), ('todo_shared', 'Todo Shared 🤝'), ('todo_accepted', 'Todo Accepted ✅'), ('todo_rejected', 'Todo Rejected ❌'), ('task_created', 'Ticket Created 🎫'), ('task_assigned', 'Ticket Assigned 📌'), ('task_updated', 'Ticket Updated 🔄'), ('task_status', 'Status Changed ⚡'), ('comment_added', 'Comment Added 💬'), ('chat_message', 'Team Chat Message 💬'), ('system', 'System Alert 🔔')], default='system', max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
