# Generated by Django 6.0.3 on 2026-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completion_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
