# Generated by Django 5.2.3 on 2026-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privileges',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
